---
version: 2.0
workflows:
  version: 2
  tests:
    jobs:
      - node8:
          filters:
            tags:
              only: /.*/
      - node9:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - node8
            - node9
          filters:
            tags:
              only: /.*/
      - docs:
          requires:
            - node8
            - node9
          filters:
            tags:
              only: /.*/

jobs:
  node8:
    docker:
      - image: node:8@sha256:a4c4106ddda19c2c228cbdfbc0f0d7a5f27c383b0486f88fc2c2c40153763cf5
        user: node
    steps: &unit_tests_steps
      - checkout
      - run: &npm_install
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Run unit tests.
          command: npm test
      - run:
          name: Submit coverage data to codecov.
          command: node_modules/.bin/codecov
          when: always
  node9:
    docker:
      - image: node:9@sha256:0f2443df7bd7e207a32f3eb8f827fe2648152254cf02e5ecb3f30fc1c5e5659b
        user: node
    steps: *unit_tests_steps
  lint:
    docker:
      - image: node:8@sha256:a4c4106ddda19c2c228cbdfbc0f0d7a5f27c383b0486f88fc2c2c40153763cf5
        user: node
    steps:
      - checkout
      - run: *npm_install
      - run:
          name: Run linting.
          command: npm run lint

  docs:
    docker:
      - image: node:8@sha256:a4c4106ddda19c2c228cbdfbc0f0d7a5f27c383b0486f88fc2c2c40153763cf5
        user: node
    steps:
      - checkout
      - run: *npm_install
      - run:
          name: Build documentation.
          command: npm run docs
